/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/
-- Find total customers by countries
SELECT 
	COUNT(customer_id) AS Total_customers,
	country
FROM gold.dim_customers
GROUP BY country
ORDER BY Total_customers DESC


-- Find total customers by gender
SELECT 
	COUNT(customer_id) AS Total_customers,
	gender
FROM gold.dim_customers
GROUP BY gender
ORDER BY Total_customers DESC


-- Find total products by category
SELECT
	COUNT(product_key) AS Total_products,
	category
FROM gold.dim_products
GROUP BY category
ORDER BY Total_products DESC

-- What is the average costs in each category?
SELECT
	AVG(cost) AS Avg_cost,
	category
FROM gold.dim_products
GROUP BY category
ORDER BY Avg_cost DESC


-- What is the total revenue generated for each category?
SELECT
	SUM(f.sales_amount) AS Total_revenue,
	p.category
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY Total_revenue DESC


-- What is the total revenue generated by each customer?
SELECT
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS Total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.customer_key,
		c.first_name,
		c.last_name
ORDER BY Total_revenue DESC

-- What is the distribution of sold items across countries?
SELECT
	c.country,
	SUM(f.quantity) AS sold_items
FROM gold.dim_customers c
RIGHT JOIN gold.fact_sales f
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY sold_items DESC




